apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisService.name }}
spec:
  selector:
    {{ .Values.redisService.selector | toYaml | nindent 4 }}
  {{- with .Values.redisService.ports }}
  ports:
  {{ toYaml . | nindent 4 }}
  {{- end }}
 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redashService.name }}
spec:
  selector:
    app: {{ .Values.server.matchLabels.app }}
  {{- with .Values.redashService.ports }}
  ports:
  {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.redashService.type }}
  type: {{ . | quote }}
  {{- end }}
